### ISSUE TITLE
Update how to run

### ISSUE THREAD

**Issue by BEASTGR** [atharval1/precision-agriculture-using-machine-learning#1]
Plz update how to run this project...it will help to us

**Comment by atharval1** [comment]
> Plz update how to run this project...it will help to us

please check my video https://youtu.be/kU0nf-rzusE

**Comment by BEASTGR** [comment]
Can I know how to deploy this project to local and run that ...

**Comment by atharval1** [comment]
what video https://www.youtube.com/watch?v=kU0nf-rzusE 
hear all steps are mentioned
